export const collections = [
  'cryptopunks',
  'boredapeyachtclub',
  'mutant-ape-yacht-club',
  'otherdeed',
  'somethingtoken',
  'coolmans-universe',
  'asm-brains',
  'cypher-drop-1',
  'renga-black-box',
  'mcgoblinwtf',
  'exclusible-penthouse-v2',
  'ey3k0n-first-edition',
  'nft-worlds',
];
